# Generated by Django 5.2.2 on 2025-09-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_useraccount_is_doctor_useraccount_is_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="is_doctor",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="is_patient",
        ),
    ]
