# Generated by Django 5.2.2 on 2025-09-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_useraccount_is_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="is_patient",
            field=models.BooleanField(default=False),
        ),
    ]
