# Generated by Django 5.2.2 on 2025-08-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={"ordering": ["-date_achieved"]},
        ),
    ]
