# Generated by Django 5.1 on 2024-10-21 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="message",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
