# Generated by Django 5.1 on 2024-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_alter_appointment_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
