# Generated by Django 5.2.2 on 2025-06-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(null=True, upload_to="services/images/"),
        ),
    ]
