# Generated by Django 5.2.2 on 2025-06-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_alter_service_options_service_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(upload_to="services/images/"),
        ),
    ]
