# Generated by Django 5.1 on 2024-10-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="doctor_at",
            field=models.CharField(
                default="iMedical Central Clinic, LA", max_length=100
            ),
        ),
    ]
