# Generated by Django 5.1 on 2024-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_rename_happy_clients_doctor_happy_patients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("cardiology", "Cardiology Doctor"),
                    ("neurology", "Neurology Doctor"),
                    ("orthopedics", "Orthopedics Doctor"),
                    ("pediatrics", "Pediatrics Doctor"),
                    ("dermatology", "Dermatology Doctor"),
                    ("leading diagnostic", "Leading Diagnostic Doctor"),
                    ("consultant dentist", "Consultant Dentist"),
                ],
                max_length=50,
            ),
        ),
    ]
