# Generated by Django 5.2.2 on 2025-06-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctor_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
