# Generated by Django 5.1 on 2024-10-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0006_alter_doctor_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="shadow",
            field=models.BooleanField(default=False),
        ),
    ]
