# Generated by Django 5.1 on 2024-10-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0007_doctor_shadow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"ordering": ["date_joined"]},
        ),
    ]
